name: Deploy to Dev Org

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Dev Org
    runs-on: ubuntu-latest

    steps:
    # 1. Setup job
    - name: Start Job
      run: echo "Starting deployment job..."

    # 2. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 3. Get branch name
    - name: Get branch name
      id: get_branch
      run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

    # 4. Install Salesforce CLI
    - name: Install Salesforce CLI
      run: |
        npm install --global @salesforce/cli
        sf --version

    # 5. Map branch to environment
    - name: Map branch to environment
      id: env_map
      run: |
        if [[ "${{ steps.get_branch.outputs.branch_name }}" == "main" ]]; then
          echo "env=dev" >> $GITHUB_OUTPUT
        else
          echo "Unsupported branch" && exit 1
        fi

    # 6. Authenticate to dev org (use SFDX Auth URL stored in GitHub Secrets)
    - name: Authenticate to Dev Org
      run: |
        echo "${{ secrets.SFDX_AUTH_URL_DEV }}" > authfile.txt
        sf org login sfdx-url --sfdx-url-file authfile.txt --alias dev --set-default
        sf org display --target-org dev
      env:
        SFDX_AUTH_URL_DEV: ${{ secrets.SFDX_AUTH_URL_DEV }}

    # 7. Run deployment on target org -> dev
    - name: Deploy Source to Dev Org
      run: |
        sf project deploy start --target-org dev --source-dir force-app

    # 8. Post checkout code / cleanup
    - name: Cleanup auth file
      run: rm authfile.txt

    # 9. Complete job
    - name: Deployment Completed
      run: echo "Deployment process completed successfully."
